---
kind: pipeline
type: docker
name: lint

steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-debian
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile
    when:
      status:
        - failure
        - success

  - name: Lint script
    image: koalaman/shellcheck-alpine
    pull: if-not-exists
    commands:
      - shellcheck start-transcode.sh
    when:
      status:
        - failure
        - success

trigger:
  event:
    - pull_request
    - push
  ref:
    exclude:
      - refs/heads/renovate/*

---
kind: pipeline
type: docker
name: test

steps:
  - name: docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password_ro
      repo: mwalbeck/jellyfin-livestream
      dry_run: true

trigger:
  event:
    - pull_request

depends_on:
  - lint

---
kind: pipeline
type: docker
name: build and publish

steps:
  - name: determine tags
    image: mwalbeck/determine-docker-tags
    pull: if-not-exists
    environment:
      APP_NAME: JELLYFIN
      CUSTOM_TAGS: latest
      DOCKERFILE_PATH: Dockerfile
      INCLUDE_MAJOR: negative
      VERSION_TYPE: docker_env

  - name: docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: mwalbeck/jellyfin-livestream

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - lint

---
kind: signature
hmac: 1d6c1aec32d28b7d396e433f1b391b44e0978dec9a10f0c8edbbdc5c4568b98f

...
