name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
      - uses: https://github.com/ludeeus/action-shellcheck@2.0.0

  build:
    runs-on: dind
    steps:
      - uses: actions/checkout@v4
      - name: Get docker tags
        id: tags
        shell: sh
        env:
          VERSION_TYPE: "docker_env"
          APP_NAME: "JELLYFIN"
          DOCKERFILE_PATH: "Dockerfile"
          CUSTOM_TAGS: "latest"
          INCLUDE_MAJOR: "no"
          IMAGE_NAME: "mwalbeck/jellyfin-livestream"
        run: |
          determine-docker-tags
          dockerd &
      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.tags.outputs.tags }}